[WIP] メッセージ一覧コンポーネント
Undecided-Discord/Oshavery-Front pull request #39
Opened 2021-08-29 10:50 UTC by kato-k

メッセージのデータと無限にリロードするところまで
まだtsになってない

初回で読むデータが多すぎるとエラーになるかも
CSSと逆スクロールはまだやらない

APIからどうデータを持ってくるかはサーバ待ち

2021-08-29 17:11 UTC, YukiYuigishi approved these changes

2021-08-30 07:41 UTC, YukiYuigishi commented
ファイル名を大文字から始まるキャメルケースにした方が良いのと
ファイル名がもう少し長いと助かる(わかりやすくなるので)というところ以外は多分大丈夫です

2021-08-30 08:29 UTC, sayoi341 commented on src/components/organisms/ChannelMessages.tsx
> +const Messages: React.FC = (props) => {
- FCをreactからインポートしてください💦一応統一します。
- このコンポーネントはpropsがないので()だけで大丈夫です。

2021-08-30 08:29 UTC, sayoi341 commented on src/components/organisms/ChannelMessages.tsx
> +  const [state, setState] = React.useState<State>({messages: []})
useStateもreactからインポートでお願いします。

2021-08-30 08:32 UTC, YukiYuigishi requested changes

2021-08-30 08:32 UTC, YukiYuigishi commented on src/components/molecules/ChannelMessage.tsx
> +const Message: FC<Props> = (props) => {
ファイル名が変わったのでコンポーネント名を変えてください

2021-08-30 08:32 UTC, YukiYuigishi commented on src/components/molecules/ChannelMessage.tsx
> +export default Message
同上

2021-08-30 08:35 UTC, kato-k commented
なおしました(たぶん

2021-08-30 08:38 UTC, kato-k commented
すいません

2021-08-30 08:42 UTC, sayoi341 approved these changes

2021-08-30 09:09 UTC, kato-k commented
なおしましta

2021-08-30 09:11 UTC, YukiYuigishi approved these changes

2021-08-30 09:14 UTC, sayoi341 approved these changes

2021-08-30 09:17 UTC, merged